name: pokeflutter
description: A sample Flutter APP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx:
  http:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen:

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball.png
    - assets/images/pokeball_dark.png

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
